{
  "checkpoints": [
    "{\n  \"trainable_name\": \"PPO\",\n  \"trial_id\": \"e7358_00000\",\n  \"config\": {\n    \"framework\": \"torch\",\n    \"env\": \"stelios\"\n  },\n  \"local_dir\": \"/root/ray_results/stelios\",\n  \"evaluated_params\": {},\n  \"experiment_tag\": \"0\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 1,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595d2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d94287d94288c0343505594473ff00000000000008c0347505594470000000000000000757d94286808473ff00000000000006809470000000000000000757d94286808473ff0000000000000680947000000000000000075658c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1631642969.264224,\n  \"logdir\": \"/root/ray_results/stelios/PPO_stelios_e7358_00000_0_2021-09-14_11-09-29\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/root/ray_results/stelios/PPO_stelios_e7358_00000_0_2021-09-14_11-09-29/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py\\\", line 739, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py\\\", line 746, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py\\\", line 82, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/worker.py\\\", line 1623, in get\\n    raise value\\nray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \\u001b[36mray::PPO.__init__()\\u001b[39m (pid=8691, ip=172.17.0.2)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py\\\", line 136, in __init__\\n    Trainer.__init__(self, config, env, logger_creator)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py\\\", line 592, in __init__\\n    super().__init__(config, logger_creator)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py\\\", line 103, in __init__\\n    self.setup(copy.deepcopy(self.config))\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py\\\", line 146, in setup\\n    super().setup(config)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py\\\", line 739, in setup\\n    self._init(self.config, self.env_creator)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py\\\", line 175, in _init\\n    num_workers=self.config[\\\"num_workers\\\"])\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py\\\", line 827, in _make_workers\\n    logdir=self.logdir)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/worker_set.py\\\", line 85, in __init__\\n    lambda p, pid: (pid, p.observation_space, p.action_space)))\\nray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \\u001b[36mray::RolloutWorker.__init__()\\u001b[39m (pid=8692, ip=172.17.0.2)\\n  File \\\"/usr/lib/python3.7/importlib/__init__.py\\\", line 127, in import_module\\n    return _bootstrap._gcd_import(name[level:], package, level)\\n  File \\\"<frozen importlib._bootstrap>\\\", line 1006, in _gcd_import\\n  File \\\"<frozen importlib._bootstrap>\\\", line 983, in _find_and_load\\n  File \\\"<frozen importlib._bootstrap>\\\", line 965, in _find_and_load_unlocked\\nModuleNotFoundError: No module named 'gym_oaas'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::RolloutWorker.__init__()\\u001b[39m (pid=8692, ip=172.17.0.2)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/rollout_worker.py\\\", line 401, in __init__\\n    self.env = env_creator(env_context)\\n  File \\\"nn_scheduler.py\\\", line 53, in env_creator\\n    environment = gym.make('gym_oaas:oaas-v0', floor_plan=floor_plan_real, agent_skills=agent_skills_2task)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py\\\", line 184, in make\\n    return registry.make(id, **kwargs)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py\\\", line 105, in make\\n    spec = self.spec(path)\\n  File \\\"/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py\\\", line 135, in spec\\n    mod_name\\ngym.error.Error: A module (gym_oaas) was specified for the environment but was not found, make sure the package is installed with `pip install` before calling `gym.make()`\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_to_cloud\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 16,
    "_metric": null,
    "_total_time": 0,
    "_iteration": 6,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/root/ray_results/stelios",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1631642969.092198,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2021-09-14_11-09-29",
    "checkpoint_file": "/root/ray_results/stelios/experiment_state-2021-09-14_11-09-29.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1631642969.092198,
    "timestamp": 1631642969.2244232
  }
}